In [20]:
import pandas as pd
import numpy as np
import os
import glob

In [21]:
ctrls = glob.glob('/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/*.miso')
ctrls = sorted(ctrls)
ctrls

['/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/hepg2_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEall_0.5_20170401.psi.nr.wensg.tpm1.miso',
 '/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/hepg2_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEcenter_0.5_20170401.psi.nr.wensg.tpm1.miso',
 '/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/hepg2_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.strict_CE_all_20170401.psi.nr.wensg.tpm1.miso',
 '/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/k562_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEall_0.5_20170401.psi.nr.wensg.tpm1.miso',
 '/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/k562_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEcenter_0.5_20170401.psi.nr.wensg.tpm1.miso',
 '/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/k562_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.strict_CE_all_20170401.psi.nr.wensg.tpm1.miso']

In [23]:
script = '/home/bay001/projects/codebase/rbp-maps/maps/plot_peak_ericbg.py'
bedfile = '/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/272.01v02.IDR.out.0102merged.bed'
cmd = 'python {} '.format(script)
cmd = cmd + '-i {} '.format(bedfile)
cmd = cmd + '-o {} '.format(bedfile + '.png')
cmd = cmd + '-m '
for c in ctrls:
    cmd = cmd + '{} '.format(c)
cmd

'python /home/bay001/projects/codebase/rbp-maps/maps/plot_peak_ericbg.py -i /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/272.01v02.IDR.out.0102merged.bed -o /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/272.01v02.IDR.out.0102merged.bed.png -m /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/hepg2_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEall_0.5_20170401.psi.nr.wensg.tpm1.miso /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/hepg2_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEcenter_0.5_20170401.psi.nr.wensg.tpm1.miso /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/hepg2_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.strict_CE_all_20170401.psi.nr.wensg.tpm1.miso /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/k562_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEall_0.5_20170401.psi.nr.wensg.tpm1.miso /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/k562_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.nSEcenter_0.5_20170401.psi.nr.wensg.tpm1.miso /home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/k562_brenton-graveley_ambiguous_bams_for_integrated_analysis.txt.strict_CE_all_20170401.psi.nr.wensg.tpm1.miso '

In [18]:
eric = pd.read_table('/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/test.bed', index_col=0, names=['a'])
brian = pd.read_table('/home/bay001/projects/maps_20160420/analysis/tests/eric_new_ctrls/272.01v02.IDR.out.0102merged.bed.hepg2-nse-all.txt', names=['b'])

In [19]:
pd.concat([eric,brian], axis=1)

        a    b
0      22   22
1      21   21
2      21   21
3      18   18
4      18   18
5      19   19
6      19   19
7      19   19
8      19   19
9      20   20
10     21   21
11     21   21
12     21   21
13     21   21
14     20   20
15     19   19
16     19   19
17     18   18
18     19   19
19     19   19
20     19   19
21     19   19
22     19   19
23     18   18
24     17   17
25     17   17
26     18   18
27     17   17
28     16   16
29     15   15
...   ...  ...
1374  164  164
1375  163  163
1376  162  162
1377  161  161
1378  159  159
1379  156  156
1380  155  155
1381  155  155
1382  151  151
1383  149  149
1384  147  147
1385  143  143
1386  136  136
1387  133  133
1388  126  126
1389  119  119
1390  116  116
1391  111  111
1392  108  108
1393  104  104
1394   99   99
1395   92   92
1396   89   89
1397   85   85
1398   79   79
1399   77   77
1400   71   71
1401   64   64
1402   60   60
1403   57   57

[1404 rows x 2 columns]